version: "3"

tasks:
  install-linter:
    desc: Install golangci-lint based on the GOOS value from go env
    cmds:
      - |
        GOOS=$(go env GOOS)
        case "$GOOS" in
          "windows")
            if command -v choco > /dev/null; then
              echo "Installing golangci-lint with Chocolatey..."
              choco install golangci-lint
              exit 0
            else
              echo "Error: Chocolatey is not installed. Please install it first: https://chocolatey.org/install"
              exit 1
            fi
            ;;
          "darwin")
            if command -v brew > /dev/null; then
              echo "Installing golangci-lint with Homebrew..."
              brew install golangci-lint
              exit 0
            else
              echo "Error: Homebrew is not installed. Please install it first: https://brew.sh/"
              exit 1
            fi
            ;;
          "linux")
            if [ -f /etc/os-release ]; then
              . /etc/os-release
              if [ "$ID" = "ubuntu" ]; then
                echo "Ubuntu detected. Installing golangci-lint using snap..."
                sudo snap install golangci-lint --classic
                exit 0
              else
                echo "Linux detected, but not Ubuntu. Please install golangci-lint using your package manager."
                echo "Examples:"
                echo "  apt: sudo apt install golangci-lint"
                echo "  yum: sudo yum install golangci-lint"
                echo "  pacman: sudo pacman -S golangci-lint"
                exit 0
              fi
            else
              echo "Linux detected, but OS information could not be determined."
              echo "Please install golangci-lint using your package manager."
              exit 0
            fi
            exit 1
            ;;
          *)
            echo "Unsupported OS: $GOOS"
            exit 1
            ;;
        esac
  lint:
    desc: Run linters using golangci-lint
    cmds:
      - golangci-lint run --config .golangci.yml
    silent: true
  tests:
    desc: Run unit app tests
    cmds:
      - go test -v ./... --count=1
    silent: true
  up:
    desc: Run app suite in containers
    cmds:
      - docker-compose up --build --detach
    silent: true
  down:
    desc: Stop app suite
    cmds:
      - docker-compose down
    silent: true
  swissknife:
    desc: Get in swissknife container
    cmds:
      - docker-compose exec swissknife sh
    silent: true
